import { DrugKnowledgeItem } from "./slmPharmacistModel";

/**
 * DawaSnap AI - Expanded On-Device Clinical Pharmacology Dataset
 * Trained on essential medicines, brand synonyms, contraindications, and multi-drug interaction graphs.
 */
export const EXPANDED_CLINICAL_DRUGS: DrugKnowledgeItem[] = [
  {
    name: "Diclofenac",
    genericName: "Diclofenac Sodium / Potassium",
    synonyms: ["voveran", "voveran sr", "voltaren", "diclogesic", "dynapar", "nac", "reactin"],
    category: "Pain Relief",
    defaultForm: "tablet",
    typicalDosages: ["50mg", "75mg", "100mg SR", "gel 1%"],
    indications: ["severe arthritis", "acute muscle sprain", "post-surgery pain", "sciatica", "rheumatic pain", "gout", "kamar dard", "tez dard"],
    usageInstructions: "Take 1 tablet after a full meal with water. Never take on an empty stomach. Topically apply gel gently without vigorous rubbing.",
    timing: "After Meals",
    contraindications: ["Active gastric ulceration", "Severe coronary artery disease", "Third-trimester pregnancy", "Severe renal impairment"],
    interactions: ["Aspirin", "Warfarin", "ACE inhibitors", "Lithium"],
    sideEffects: ["Gastric burning", "Acid dyspepsia", "Fluid retention"],
    hinglishSummary: "Tez jod (joint) aur kamar ke dard ke liye asardar NSAID dawa hai. Hamesha khana khane ke baad lein.",
    tags: ["NSAID", "Severe Pain", "Joint Pain", "Prescription"]
  },
  {
    name: "Cefixime",
    genericName: "Cefixime Trihydrate",
    synonyms: ["zifi", "taxim-o", "ceftas", "mahacef", "omnicef", "topcef"],
    category: "Antibiotics",
    defaultForm: "tablet",
    typicalDosages: ["200mg", "100mg", "100mg/5ml suspension"],
    indications: ["typhoid fever", "urinary tract infection", "tonsillitis", "bronchitis", "otitis media (ear infection)", "gonococcal infection"],
    usageInstructions: "Take 1 tablet (200mg) twice daily after meals for 5 to 7 days as prescribed by your doctor. Complete the full course.",
    timing: "After Meals (Twice Daily)",
    contraindications: ["Known cephalosporin hypersensitivity", "Severe penicillin anaphylaxis history"],
    interactions: ["Warfarin (increased bleeding tendency)", "Carbamazepine"],
    sideEffects: ["Diarrhea", "Loose stools", "Abdominal discomfort"],
    hinglishSummary: "Ye 3rd generation cephalosporin antibiotic hai jo typhoid, gale aur peshab ke infection me di jaati hai. Course poora karein.",
    tags: ["Antibiotic", "Typhoid", "UTI", "Prescription"]
  },
  {
    name: "Doxycycline",
    genericName: "Doxycycline Hyclate",
    synonyms: ["doxil", "doxy-1", "vibramycin", "monodox", "microdox"],
    category: "Antibiotics",
    defaultForm: "capsule",
    typicalDosages: ["100mg"],
    indications: ["acne vulgaris", "respiratory infections", "malaria prophylaxis", "chlamydia", "cholera", "rickettsial fever", "scrub typhus"],
    usageInstructions: "Take with a full glass of water while sitting or standing upright. Do NOT lie down for at least 30 minutes after taking to prevent esophageal ulceration.",
    timing: "With Food & Full Glass of Water (Stay Upright)",
    contraindications: ["Pregnancy", "Nursing mothers", "Children < 8 years (causes tooth discoloration)"],
    interactions: ["Iron / Calcium supplements (space by 2-3 hours)", "Antacids"],
    sideEffects: ["Esophageal irritation if taken dry", "Sunlight photosensitivity", "Nausea"],
    hinglishSummary: "Chehre ke keel-muhase (acne) aur bacterial infection ke liye. Baithe ya khade hokar poore ek glass paani ke sath lein, turant na soyein.",
    tags: ["Antibiotic", "Acne", "Infection", "Capsule"]
  },
  {
    name: "Esomeprazole",
    genericName: "Esomeprazole Magnesium",
    synonyms: ["nexium", "esomac", "sompraz", "izra", "esoz"],
    category: "Digestive",
    defaultForm: "tablet",
    typicalDosages: ["20mg", "40mg"],
    indications: ["severe gerd", "erosive esophagitis", "h. pylori eradication", "gastric acid hypersecretion", "chronic heartburn"],
    usageInstructions: "Take 1 tablet once daily in the morning, 30 to 60 minutes before breakfast with water.",
    timing: "30-60 mins Before Breakfast (Empty Stomach)",
    contraindications: ["Hypersensitivity to PPIs"],
    interactions: ["Clopidogrel (may reduce antiplatelet activation)", "Diazepam", "Iron"],
    sideEffects: ["Headache", "Flatulence", "Abdominal pain"],
    hinglishSummary: "Severe acidity aur food-pipe me jalan ke liye high-potency PPI hai. Subah khali pet lein.",
    tags: ["Acidity", "GERD", "Digestive", "Empty Stomach"]
  },
  {
    name: "Ranitidine / Famotidine",
    genericName: "Famotidine 20mg / 40mg",
    synonyms: ["facid", "famocid", "pepcid", "aciloc", "rantac", "zantac"],
    category: "Digestive",
    defaultForm: "tablet",
    typicalDosages: ["20mg", "40mg"],
    indications: ["mild acidity", "evening heartburn", "preventing acid reflux at night", "stomach burning"],
    usageInstructions: "Take 1 tablet before dinner or at bedtime with water.",
    timing: "Bedtime or Before Evening Meal",
    contraindications: ["Severe renal failure (requires dose adjustment)"],
    interactions: ["Antacids (space by 1 hour)"],
    sideEffects: ["Mild headache", "Dizziness", "Constipation or diarrhea"],
    hinglishSummary: "H2 blocker dawa hai jo raat ki acidity aur gas ko rokti hai. Raat ke khane se pehle ya sone se pehle lein.",
    tags: ["Acidity", "Heartburn", "Digestive", "Bedtime"]
  },
  {
    name: "Fexofenadine",
    genericName: "Fexofenadine Hydrochloride",
    synonyms: ["allegra", "fexo", "fexova", "histafree", "altiva"],
    category: "Allergy",
    defaultForm: "tablet",
    typicalDosages: ["120mg", "180mg", "30mg/5ml"],
    indications: ["seasonal allergic rhinitis", "sneezing", "skin hives", "itching", "non-drowsy allergy relief", "chheenk", "khujli"],
    usageInstructions: "Take 1 tablet once daily with water. Avoid taking with fruit juices (apple, orange, grapefruit) as they decrease absorption.",
    timing: "Morning or Daytime (Non-Drowsy)",
    contraindications: ["Known hypersensitivity"],
    interactions: ["Aluminium & Magnesium antacids (take 2 hours apart)", "Fruit juices"],
    sideEffects: ["Mild headache", "Nausea (very low drowsiness rate)"],
    hinglishSummary: "Ye non-drowsy allergy dawa hai jisse neend nahi aati. Din me ek baar lein. Fruit juice ke sath na lein.",
    tags: ["Allergy", "Non-Drowsy", "Sneezing", "Daytime"]
  },
  {
    name: "Clopidogrel",
    genericName: "Clopidogrel Bisulfate",
    synonyms: ["plavix", "clopilet", "ceruvin", "deplatt", "clopivas"],
    category: "Heart",
    defaultForm: "tablet",
    typicalDosages: ["75mg"],
    indications: ["stent protection", "stroke prevention", "peripheral artery disease", "myocardial infarction prevention", "khoon patla karna"],
    usageInstructions: "Take 1 tablet once daily at the same time with or without food. Do not stop without consulting your cardiologist.",
    timing: "Fixed time daily",
    contraindications: ["Active pathological bleeding (such as peptic ulcer or intracranial hemorrhage)"],
    interactions: ["Omeprazole/Esomeprazole (prefer Pantoprazole instead)", "NSAIDs", "Warfarin"],
    sideEffects: ["Easy bruising", "Nosebleeds", "Bleeding gums"],
    hinglishSummary: "Heart stent lagne ke baad khoon ke thakke (clots) jamne se rokne ke liye sabse mahatvapoorna dawa hai.",
    tags: ["Blood Thinner", "Cardiovascular", "Heart", "Prescription"]
  },
  {
    name: "Losartan",
    genericName: "Losartan Potassium",
    synonyms: ["cozaar", "losacar", "losakind", "covance", "repace"],
    category: "Heart",
    defaultForm: "tablet",
    typicalDosages: ["25mg", "50mg", "100mg"],
    indications: ["hypertension", "diabetic nephropathy", "stroke reduction in hypertensive patients with LVH"],
    usageInstructions: "Take 1 tablet once daily with or without food. Maintain regular BP monitoring.",
    timing: "Morning / Fixed Time",
    contraindications: ["Pregnancy", "Concomitant aliskiren in diabetes"],
    interactions: ["Potassium-sparing diuretics", "Potassium supplements", "NSAIDs"],
    sideEffects: ["Dizziness", "Back pain", "Nasal congestion"],
    hinglishSummary: "High Blood Pressure aur kidney ki suraksha ke liye ARB dawa hai. Roz subah ek samay par lein.",
    tags: ["Blood Pressure", "Heart", "Hypertension", "Daily"]
  },
  {
    name: "Glimepiride",
    genericName: "Glimepiride",
    synonyms: ["amaryl", "zoryl", "glimy", "diaprime", "glypride"],
    category: "Diabetes",
    defaultForm: "tablet",
    typicalDosages: ["1mg", "2mg", "3mg", "4mg"],
    indications: ["type 2 diabetes", "elevated blood glucose", "pancreatic insulin secretion stimulate karna"],
    usageInstructions: "Take once daily immediately before or with the first substantial meal of the day (usually breakfast). Always have meals on time to avoid hypoglycemia.",
    timing: "With Breakfast (First Main Meal)",
    contraindications: ["Type 1 diabetes", "Diabetic ketoacidosis", "Severe hepatic or renal impairment"],
    interactions: ["Beta-blockers (masks hypoglycemia symptoms)", "Fluconazole", "Alcohol"],
    sideEffects: ["Hypoglycemia (low blood sugar - shakiness, sweating, dizziness)", "Weight gain"],
    hinglishSummary: "Sugar kam karne ke liye. Hamesha nashta/khana khate waqt lein. Khana miss na karein varna sugar low ho sakti hai.",
    tags: ["Diabetes", "Blood Sugar", "Breakfast", "Prescription"]
  },
  {
    name: "Levofloxacin",
    genericName: "Levofloxacin Hemihydrate",
    synonyms: ["levaquin", "levomac", "l-cin", "glevo", "levoday"],
    category: "Antibiotics",
    defaultForm: "tablet",
    typicalDosages: ["250mg", "500mg", "750mg"],
    indications: ["pneumonia", "acute sinusitis", "complicated uti", "chronic bronchitis flare", "skin bacterial infections"],
    usageInstructions: "Take 1 tablet once daily with plenty of fluids, at least 2 hours before or after magnesium/aluminum antacids or iron/zinc supplements.",
    timing: "Fixed time daily with lots of water",
    contraindications: ["History of tendon rupture", "Myasthenia gravis", "QT prolongation", "Epilepsy"],
    interactions: ["Antacids", "Sucralfate", "NSAIDs (seizure risk)", "Warfarin"],
    sideEffects: ["Nausea", "Headache", "Tendon pain/stiffness (stop immediately if Achilles tendon hurts)"],
    hinglishSummary: "Tez bacterial aur chest infection ke liye fluoroquinolone antibiotic hai. Khoob paani piyein.",
    tags: ["Antibiotic", "Pneumonia", "UTI", "Prescription"]
  },
  {
    name: "Pregabalin",
    genericName: "Pregabalin",
    synonyms: ["lyrica", "pregalin", "maxgalin", "neugaba", "prebaxe"],
    category: "Neurological",
    defaultForm: "capsule",
    typicalDosages: ["75mg", "150mg", "300mg"],
    indications: ["neuropathic pain", "diabetic nerve pain", "fibromyalgia", "sciatica nerve burning", "tingling in hands & feet", "nason ka dard"],
    usageInstructions: "Take 1 capsule at bedtime as prescribed. Do not stop abruptly as withdrawal symptoms can occur.",
    timing: "Bedtime",
    contraindications: ["Known hypersensitivity", "Severe heart failure without monitoring"],
    interactions: ["Opioids (severe respiratory depression)", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Dizziness", "Drowsiness", "Weight gain", "Peripheral swelling"],
    hinglishSummary: "Nason ke dard (nerve pain), jhanjhanahat aur diabetic neuropathy ke liye. Raat ko sone se pehle li jaati hai.",
    tags: ["Nerve Pain", "Neurology", "Bedtime", "Prescription"]
  },
  {
    name: "Methylcobalamin (Vitamin B12)",
    genericName: "Mecobalamin / Methylcobalamin",
    synonyms: ["neurobion", "methycobal", "nurokind", "rejunex", "bicopep"],
    category: "Vitamins",
    defaultForm: "tablet",
    typicalDosages: ["1500mcg", "500mcg"],
    indications: ["vitamin b12 deficiency", "peripheral neuropathy", "numbness in fingers/toes", "fatigue", "pernicious anemia"],
    usageInstructions: "Take 1 tablet daily after breakfast or lunch with water.",
    timing: "After Meals",
    contraindications: ["Hypersensitivity"],
    interactions: ["Metformin / Omeprazole (long term use reduces B12 absorption)"],
    sideEffects: ["Extremely safe, rarely mild nausea or rash"],
    hinglishSummary: "Nason ki taakat aur Vitamin B12 ki kami ke liye. Haath-paanv ke sunn-pan ko theek karti hai.",
    tags: ["Vitamin B12", "Nerves", "Vitamins", "Daily"]
  },
  {
    name: "Tramadol + Paracetamol",
    genericName: "Tramadol HCl 37.5mg + Paracetamol 325mg",
    synonyms: ["ultracet", "tramazac plus", "calpol-t", "dolzero", "uriket"],
    category: "Pain Relief",
    defaultForm: "tablet",
    typicalDosages: ["37.5mg/325mg"],
    indications: ["moderate to severe acute pain", "post-operative pain", "severe fracture pain", "dental extraction pain"],
    usageInstructions: "Take 1 tablet strictly as advised by a doctor. Avoid operating machinery or driving due to sedative effects.",
    timing: "After Meals / Strictly as Prescribed",
    contraindications: ["Acute intoxication with alcohol or sedatives", "Severe respiratory depression", "Epilepsy"],
    interactions: ["SSRIs / Antidepressants (risk of serotonin syndrome)", "Alcohol", "Sedatives"],
    sideEffects: ["Drowsiness", "Dizziness", "Nausea", "Constipation"],
    hinglishSummary: "Jab sadharan painkiller se aaram na mile tab doctor dwara prescribe ki jaane wali strong painkiller hai.",
    tags: ["Severe Pain", "Prescription", "Sedative", "Controlled"]
  },
  {
    name: "Sucralfate",
    genericName: "Sucralfate",
    synonyms: ["sucrafil", "pepcoat", "carafate", "sucrace", "recofast"],
    category: "Digestive",
    defaultForm: "liquid",
    typicalDosages: ["1000mg/5ml suspension", "1g tablet"],
    indications: ["peptic ulcer healing", "gastric erosion", "acid mucosal protection", "food pipe ulcers"],
    usageInstructions: "Take 10ml (or 1 tablet) on an empty stomach, 1 hour before meals and at bedtime. It forms a physical protective coat over ulcers.",
    timing: "1 hour Before Meals & Bedtime (Empty Stomach)",
    contraindications: ["Severe chronic kidney disease (aluminum accumulation)"],
    interactions: ["Fluoroquinolones", "Digoxin", "Warfarin (take 2 hours before sucralfate)"],
    sideEffects: ["Constipation", "Dry mouth"],
    hinglishSummary: "Pet ke chhalon (ulcers) par ek suraksha layer bana leti hai. Khana khane se 1 ghanta pehle lein.",
    tags: ["Ulcer", "Digestive", "Empty Stomach", "Suspension"]
  },
  {
    name: "Lactulose",
    genericName: "Lactulose",
    synonyms: ["duphalac", "cremaffin plus", "looz", "evict", "laxose"],
    category: "Digestive",
    defaultForm: "liquid",
    typicalDosages: ["15ml", "30ml"],
    indications: ["chronic constipation", "hard stools", "hepatic encephalopathy", "post-surgery gentle bowel movement", "kabz"],
    usageInstructions: "Take 15ml to 30ml once daily at night or with breakfast. Drink plenty of water throughout the day. May take 24-48 hours for effect.",
    timing: "Bedtime or Morning (with glass of water)",
    contraindications: ["Galactosemia", "Bowel obstruction"],
    interactions: ["Antacids (may reduce osmotic laxative acidification)"],
    sideEffects: ["Flatulence and gas in the first 2-3 days", "Abdominal cramps if dose is high"],
    hinglishSummary: "Pet saaf karne aur kabz (constipation) ko bina kisi aadat ke aasan banane ke liye sabse safe syrup hai.",
    tags: ["Constipation", "Digestive", "Kabz", "Syrup"]
  },
  {
    name: "Clotrimazole / Terbinafine",
    genericName: "Clotrimazole 1% / Terbinafine 1%",
    synonyms: ["candid", "canesten", "terbicip", "sebifin", "daktarin"],
    category: "Dermatological",
    defaultForm: "other",
    typicalDosages: ["Cream 1% topical", "Dusting powder 1%"],
    indications: ["fungal skin infection", "ringworm", "athlete's foot", "jock itch", "sweat rash", "daadh", "khujli"],
    usageInstructions: "Clean and dry the affected area thoroughly. Apply a thin layer twice daily for 2 to 4 weeks. Continue for 1 week after symptoms resolve.",
    timing: "Morning & Night after bathing",
    contraindications: ["Hypersensitivity to azole antifungals"],
    interactions: ["None significant with topical application"],
    sideEffects: ["Local skin stinging or redness"],
    hinglishSummary: "Fungal infection, daadh aur pasine ki khujli ke liye. Saaf karke sukhi twacha par din me 2 baar lagayein.",
    tags: ["Fungal", "Skin", "Cream", "Topical"]
  },
  {
    name: "Fluconazole",
    genericName: "Fluconazole",
    synonyms: ["forcan", "diflucan", "flucos", "zocon", "syscan"],
    category: "Antibiotics",
    defaultForm: "tablet",
    typicalDosages: ["150mg single dose", "50mg daily", "200mg"],
    indications: ["vaginal candidiasis (yeast infection)", "oral thrush", "stubborn fungal skin infection", "fungal nail infection"],
    usageInstructions: "For simple yeast infection: Take 1 tablet (150mg) as a single oral dose with water, with or without food.",
    timing: "Single dose or as directed",
    contraindications: ["Co-administration with terfenadine, cisapride, astemizole"],
    interactions: ["Warfarin (markedly increases INR)", "Sulfonylureas (hypoglycemia risk)", "Statins"],
    sideEffects: ["Nausea", "Headache", "Abdominal pain"],
    hinglishSummary: "Yeast infection aur ziddi fungal bimariyon ke liye single dose oral tablet hai.",
    tags: ["Antifungal", "Infection", "Single Dose", "Prescription"]
  },
  {
    name: "Silver Sulfadiazine / Povidone Iodine",
    genericName: "Povidone Iodine 5% / 10% & Silver Sulfadiazine 1%",
    synonyms: ["betadine", "burnol", "silvazine", "cipladine", "megaderm"],
    category: "First Aid",
    defaultForm: "other",
    typicalDosages: ["Ointment 5%", "Solution 10%"],
    indications: ["minor burns", "scrapes", "cuts", "wound antiseptic", "preventing wound infection", "jalan", "chot"],
    usageInstructions: "Rinse wound with clean cool water. Apply gently on the cut or burn. Cover with sterile gauze if needed.",
    timing: "As needed during injury cleaning",
    contraindications: ["Iodine allergy", "Deep puncture wounds (seek ER)"],
    interactions: ["None significant topically"],
    sideEffects: ["Mild temporary staining of skin (washes off with water)"],
    hinglishSummary: "Chot, ghav aur jalne par lagane wali safe antiseptic cream/ointment hai.",
    tags: ["First Aid", "Antiseptic", "Wound", "Burns", "OTC"]
  }
];
